import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";
// import { NextRequest, NextResponse } from "next/q";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: any) {
  const {
    params: { locale },
  } = props;

  // console.log("locale test : ", Boolean(locale));

  // if (locale && !["vi", "en"].includes(locale)) {
  //   return notFound();
  // }

  return (
    <html lang={props.params.locale ? props.params.locale : "vi"}>
      <body className={inter.className}>{props.children}</body>
    </html>
  );
}
